name: Build and Deploy to Prod
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
    - uses: actions/checkout@v3
    - name: Install NodeJS
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
    - run: npm install
    - name: Build
    - run: ng build --configuration=production --base-href=/EchelonExtractor/
    - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages  
          FOLDER: dist/EchelonExtractor
           